### ISSUE TITLE
Send messages back to server?

### ISSUE THREAD

**Issue by sftpocketmine** [niekmussche/Discord-MCPE#16]
Not really an issue, but I wondering if this plugin can also send messages back to the server from discord?  If it doesn't already, could you possibly add this to the plugin? <3

**Comment by Thunder33345** [comment]
i doubt it with current structure it will only be one way, and a rewrite or so will be needed for it to be 2way and to be an actual chat bridge

**Comment by NiekertDev** [comment]
Yes @Thunder33345

**Comment by sftpocketmine** [comment]
Aww, that's what I was looking for :/

Something like https://github.com/destruc7i0n/shulker but for PE.

**Comment by Thunder33345** [comment]
yeah sadly here, no one really bothered to make an actual bridge, it's just hacks everywhere

**Comment by NiekertDev** [comment]
Maybe I'm going to try....

After 100 years xD

**Comment by Thunder33345** [comment]
:c
