### ISSUE TITLE
Fatal Error: Decleration of...

### ISSUE THREAD

**Issue by ggomezz** [niekmussche/Discord-MCPE#17]
Hello, let me make this simple.
I used this .phar - https://poggit.pmmp.io/babs/66b2
I used normal plugin installation steps (Pop it in the plugins folder and do a reload)
The stuff below is the console output:

Fatal error: Declaration of Niekert\DiscordMCPE\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, string $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar://
/root/plugins/Discord-MCPE.phar/src/Niekert/DiscordMCPE/Main.php on line 13
[20:52:02] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[20:52:02] [Server thread/EMERGENCY]: Please upload the "/root/crashdumps/Thu_Aug_3-20.52.02-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

I am running API 3.0.0-ALPHA7 on a Linux VPS
Here is the crash dump: https://pastebin.com/0TrYVZeg

**Comment by Thunder33345** [comment]
NOTE TO CONTRIBUTORS:
this is caused by the lattest strict type API

**Comment by Vaults1** [comment]
So we didn't actually support ALPHA7 properly?

**Comment by theworstdrug** [comment]
Can someone fix this?

**Comment by NiekertDev** [comment]
Sorry for late response, at holiday atm

First of all: thanks for trying my plugin! 

Going to fix it  for you as fast as I can

Note to devs: I thought "Poggit passed it so no problem" but not 😏

**Comment by ggomezz** [comment]
Alright, thank you for the continuous support through this issue!

**Comment by NiekertDev** [comment]
Can you try now? Build #23?

**Comment by ggomezz** [comment]
Alright, the startup issue has been fixed. I have not actually tried to use the plugin yet so if there appears to be some issue there then I will make sure to notify you. Thank you again!

**Comment by NiekertDev** [comment]
Okay. 

For further issues, feel free to make an issue

**Comment by theworstdrug** [comment]
Can confirm it works now! Thanks so much!


DO you have any thoughts of adding a complete bridge? Any workarounds for this?

**Comment by NiekertDev** [comment]
I need to rewrite the plugin completely to do that. Webhooks are only one way.

**Comment by NiekertDev** [comment]
@Little2Epic Can you ask your question again in "Questions" issue? So people will see it

**Comment by theworstdrug** [comment]
Alrighty
