### ISSUE TITLE
API 9

### ISSUE THREAD

**Issue by navy676aw** [niekmussche/Discord-MCPE#23]
Please update to API Alpha 9. Thank you!

**Comment by NiekertDev** [comment]
Whats the error?

**Comment by RevAtWERQ** [comment]
``[Server] Server thread/ERROR Could not load plugin 'DiscordMCPE': Incompatible API version (plugin requires one of: 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8)``

**Comment by NiekertDev** [comment]
Whats the error when you add 3.0.0-ALPHA9 in the plugin.yml file under 3.0.0-ALPHA8

**Comment by NiekertDev** [comment]
No reaction, closing
