### ISSUE TITLE
Two-Way Communication?

### ISSUE THREAD

**Issue by Subject-4** [niekmussche/Discord-MCPE#24]
Is it possible to make it so u can send messages in the discord chat to the server

**Comment by NiekertDev** [comment]
No, ATM it's only one way communication

**Comment by Subject-4** [comment]
Okay, btw nice plugin I used this other plugin which fixes outdated plugins and it's great 👍

**Comment by NiekertDev** [comment]
Which other plugin?

**Comment by Subject-4** [comment]
AllAPILoader - it let's you run outdated plugins on ur server, that's how I'm using this plugin rn
