### ISSUE TITLE
Unexpected thing

### ISSUE THREAD

**Issue by Subject-4** [niekmussche/Discord-MCPE#25]
A few weeks ago this plugin was working fine, I had chat enabled so it sends everything to discord channel but I've realised it's no longer working, the plugin is enabled and /discord works, but if I just type anything into server chat, it doesn't show on discord

**Comment by NiekertDev** [comment]
Is the webhook stil working?
Try it with this website: https://himbeer.me/discord/

**Comment by Subject-4** [comment]
Just tried it, webhook is still working

**Comment by Subject-4** [comment]
The only things that get sent to my discord channel from the mcpe server are join, quit, start, stop, and death messages, the messages that player writes no longer gets sent, it stopped working on 25th January,  an hour after some rapid spam a player did

**Comment by NiekertDev** [comment]
You did restart the server? No errors? Try putting debug on in the config

**Comment by Subject-4** [comment]
No errors show up on console, I tested with debug on too, still the same

**Comment by NiekertDev** [comment]
Just to make sure, you have it enabled in the config?

**Comment by Subject-4** [comment]
Yes

**Comment by Subject-4** [comment]
Any updates on the issue?

**Comment by NiekertDev** [comment]
Actually not

**Comment by NiekertDev** [comment]
DM me on Discord your boot log @Niekert#9833

**Comment by Subject-4** [comment]
Accept req

**Comment by NiekertDev** [comment]
Done
