### ISSUE TITLE
Update to latest API

### ISSUE THREAD

**Issue by brexmania123** [niekmussche/Discord-MCPE#26]
Hi, my name is brexmania123 and i was wondering if you could update the discord - mcpe plugin/bot. i was planning on using it on a server i help on but the version doesnt work since it isnt configured for the latest api. could you fix this. the latest version is 3.0.0-ALPHA11. If you could get this done soon i would be grateful. THX

**Comment by NiekertDev** [comment]
Hello,

It isn't my plan to update this plugin, maybe have a look at https://github.com/eDroiid/ChatToDiscord ?

**Comment by NiekertDev** [comment]
API Bumped by someone elsed, merged into master, closing.

**Comment by NiekertDev** [comment]
API Bumped by someone elsed, merged into master, closing.
