### ISSUE TITLE
Going not

### ISSUE THREAD

**Issue by jan-tennert** [niekmussche/Discord-MCPE#27]
I can not do that, I made the webhook URL clean but nothing works

**Comment by NiekertDev** [comment]
What can't you do?

**Comment by jan-tennert** [comment]
Is that right? ~~link with webhook url~~

**Comment by NiekertDev** [comment]
Set chat url to 0

**Comment by SivannOnline** [comment]
Doesn't work! Help!

**Comment by NiekertDev** [comment]
Please tell me more about the issue your having. Send your config (with webhook link removed) and the lines Discord-MCPE creates in the console

**Comment by SivannOnline** [comment]
I already done put the webhook to the config file, but it doesn't work

**Comment by NiekertDev** [comment]
Send your config (with webhook link removed) and the lines Discord-MCPE creates in console

**Comment by SivannOnline** [comment]
Hey! Chat webhook and Server webhook, different or not ?

**Comment by SivannOnline** [comment]
What I do first ? Can you tell me step by step ?

**Comment by NiekertDev** [comment]
@SivannOnline Look what I said above

**Comment by Aericio** [comment]
@SivannOnline Ensure that the webhook is in " ", or else it won't be a string.

ex: `webhook_url: "https://discordapp.com/api/webhooks/424759495323942912/uk6u1gldUwcEhn23YC74AJni8qc-gdC2JfUobAUC4WNvsb_xzZf35tgjAjoScsUo1aBx"`

**Comment by SivannOnline** [comment]
Hello, Please give me link download this plugin.

**Comment by SivannOnline** [comment]
I put link in ""

**Comment by SivannOnline** [comment]
Where I put ?

**Comment by SivannOnline** [comment]
Hey! Do you have ex. all for me?

**Comment by SivannOnline** [comment]
Now it work! but why don't see players chat ?

**Comment by NiekertDev** [comment]
It is an option in the config

**Comment by SivannOnline** [comment]
Where? Can you tell me about to show players chat in Discord ?

**Comment by NiekertDev** [comment]
In the config file under "other options" set chat to true

**Comment by SivannOnline** [comment]
I set already, but not work!

**Comment by Aericio** [comment]
You're doing something wrong then. Plugin works perfectly fine.
