### ISSUE TITLE
/reload makes plugin think server stopped

### ISSUE THREAD

**Issue by Aericio** [niekmussche/Discord-MCPE#39]
Upon using `/reload`, it sends a message to discord saying the server stopped and turned back on. 

![image](https://user-images.githubusercontent.com/16523741/43684756-b64d3a30-9841-11e8-8a2a-a2151df7ee73.png)
![image](https://user-images.githubusercontent.com/16523741/43684760-c0897cd4-9841-11e8-9446-75ef5049c115.png)

It's not really that big of an issue (could be ignored, who cares), but could probably add a new message in config for reloads.

**Comment by NiekertDev** [comment]
I don't think there's an official way to handle it, going to look into it soon

**Comment by Aericio** [comment]
How about, if reload is detected (is there something to detect that?) then just cancel the sending of those two messages?
