### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by AvgZing** [niekmussche/Discord-MCPE#5]
Make a command:
/discord [message]
and make 
args[0] = $message

**Comment by Matthww** [comment]
I could make this

**Comment by AvgZing** [comment]
@flaxues I know you could, and so could I, I just don't know if he would want me too. i could easily make it into a PR, but I didnt because I wanna see if he can do it himself (just a skill test)

**Comment by Matthww** [comment]
You could just make a PR. If he doesn't add it you still have it for your own use :)

**Comment by NiekertDev** [comment]
The plugin isn't finished yet.

I'm going to add
1. Command
2. Message on join (Look my new branch for events)
3. Message on quit
4. Message on kill
5. Message on stop
6. Message on restart
7. Debug option

**Comment by InspectorGadget** [comment]
add ticks so the server could really reboot after the owner wants it

**Comment by HimbeersaftLP** [comment]
> args[0] = $message

`$message = implode(" ", $args);`

Would be better I think

**Comment by NiekertDev** [comment]
I've succesfully finished the plugin, but there are some features that are going to be added, so not v1.0.0 but still v0.6.0.

**Comment by HimbeersaftLP** [comment]
Nice

**Comment by AvgZing** [comment]
So this can be closed now, I assume
